DELETE FROM settings;
DELETE FROM cottages;
DELETE FROM experiences;
DELETE FROM posts;
DELETE FROM faqs;
DELETE FROM gallery_items;
INSERT INTO settings (key, value) VALUES ('logo_url', '/images/RosaryNest-animated1.svg');
INSERT INTO settings (key, value) VALUES ('hero_media_type', 'video');
INSERT INTO settings (key, value) VALUES ('hero_image_url', '');
INSERT INTO settings (key, value) VALUES ('hero_video_url', '');
INSERT INTO settings (key, value) VALUES ('site_name', 'RosaryNest');
INSERT INTO settings (key, value) VALUES ('tagline', 'where stillness stays');
INSERT INTO settings (key, value) VALUES ('established_year', '2010');
INSERT INTO settings (key, value) VALUES ('phone', '+91 98477 76136');
INSERT INTO settings (key, value) VALUES ('whatsapp', '+91 98477 76136');
INSERT INTO settings (key, value) VALUES ('email', 'stay@rosarynest.com');
INSERT INTO settings (key, value) VALUES ('address_line1', '223J+GW5, Sengulam-Muthuvankudi Road, Near Little Flower Mercy Home');
INSERT INTO settings (key, value) VALUES ('address_line2', 'Anachal, Bison Valley, Munnar, Kerala 685565, India');
INSERT INTO settings (key, value) VALUES ('latitude', '10.0889');
INSERT INTO settings (key, value) VALUES ('longitude', '77.0595');
INSERT INTO settings (key, value) VALUES ('instagram_url', '');
INSERT INTO settings (key, value) VALUES ('facebook_url', '');
INSERT INTO settings (key, value) VALUES ('tripadvisor_url', '');
INSERT INTO settings (key, value) VALUES ('hours_note', 'We answer between 8 in the morning and 9 in the evening, IST. Late notes get a reply with the first pot of tea.');
INSERT INTO cottages (slug, name, tagline, description, capacity_summary, area_sqm, amenities, images, display_order, status) VALUES ('den-view-cottage', 'Den View Cottage', 'Mornings begin in the garden.', 'Den View Cottage at Rosary Nest is a cozy and well-appointed accommodation designed to offer guests a peaceful stay amidst the scenic beauty of Munnar. Set within the tranquil surroundings of the property, the cottage provides a warm and comfortable ambiance, making it an ideal choice for those looking to unwind in nature. With its charming setting and close proximity to lush greenery and misty hills, Den View Cottage ensures a relaxing retreat while still allowing easy access to nearby attractions.', '1 room, 6 guests maximum', null, '["Barbecue","Trash cans","Clothes rack","Wardrobe/Closet","Fan","Tile/Marble floor","Private bathroom","Toilet paper","Toiletries","Bathrobe","Shower","Bottle of Water","Electric kettle","Towels","TV","Linens","Bed linen","Cloth Hangars","Ceiling fan","Hand sanitizer"]', '["/images/red-cottage-front-view.png","/images/red-cottage-bed2view-1.jpg","/images/red-cottage-bed-3-1.jpg","/images/red-cottage-dining-1.jpg","/images/red-cottage-bathroom-1.jpg","/images/red-cottage-hall-1.jpg","/images/red-cottage-entrance-1.jpg"]', 1, 'published');
INSERT INTO cottages (slug, name, tagline, description, capacity_summary, area_sqm, amenities, images, display_order, status) VALUES ('tarry-cottage', 'Tarry Cottage', 'Wake up to peaceful views and lush greenery.', 'Tarry Cottage at Rosary Nest offers a comfortable and tranquil stay amidst the picturesque landscapes of Munnar. Thoughtfully designed to blend with the natural surroundings, the cottage provides a cozy and inviting atmosphere for guests seeking relaxation and privacy. Surrounded by lush greenery and serene views, it serves as an ideal retreat for nature lovers while still being conveniently accessible.', '1 room, 6 guests maximum', null, '["Air conditioning","Trash cans","Wardrobe/Closet","Fan","Tile/Marble floor","Private bathroom","Toilet paper","Toiletries","Bathrobe","Shower","Bottle of Water","Electric kettle","Linens","Towels","TV","Cloth Hangars","Bed linen","Shower gel","Hand sanitizer"]', '["/images/veranta-view-3.jpg","/images/bedroom-view-3.jpg","/images/bathroom-view-1.jpg","/images/hut-washroom-1.jpg","/images/bedroom-view2-1.jpg","/images/garden-view-wide-1.jpg","/images/veranta-view2-1.jpg"]', 2, 'published');
INSERT INTO cottages (slug, name, tagline, description, capacity_summary, area_sqm, amenities, images, display_order, status) VALUES ('sparrow-hut', 'Sparrow Hut', 'Made for togetherness, wrapped in quiet comfort.', 'Sparrow Hut at Rosary Nest is a charming and cozy accommodation designed for guests who wish to experience a peaceful stay close to nature. Set amidst the serene greenery of Munnar, the hut offers a warm and rustic ambiance while ensuring comfort and privacy. Its tranquil surroundings and scenic views make it an ideal choice for those looking to unwind and enjoy a quiet retreat.', '1 room, 3 guests maximum', null, '["Bed linen","Body soap","Bottle of Water","Ceiling fan","Cloth Hangars","Electric kettle","Fan","Free toiletries","Hand sanitizer","Linens","Private bathroom","Shower","Shower gel","Telephone","Tile/Marble floor","Toilet","Toilet paper","Toiletries","Towels","Trash cans","TV","Wardrobe/Closet"]', '["/images/hut-main-view-1.jpg","/images/hut-bed-room-1.jpg","/images/bamboo-cafe-1.jpg","/images/hut-washroom-1.jpg","/images/hut-veranda-view-1.jpg"]', 3, 'published');
INSERT INTO cottages (slug, name, tagline, description, capacity_summary, area_sqm, amenities, images, display_order, status) VALUES ('eyrie-cottage', 'Eyrie Cottage', 'A stay that feels hidden away from the world.', 'Eyrie Cottage at Rosary Nest offers a peaceful and comfortable stay set amidst the scenic hills of Munnar. Designed to provide a relaxing retreat, the cottage features a cozy ambiance complemented by the natural beauty surrounding the property. With its serene setting, fresh mountain air, and picturesque views, Eyrie Cottage is ideal for guests seeking a quiet escape while still being conveniently accessible.', '1 room, 3 guests maximum', null, '["Air conditioning","Bed linen","Body soap","Bottle of Water","Ceiling fan","Cloth Hangars","Clothes rack","Electric kettle","Fan","Free toiletries","Hand sanitizer","Private bathroom","Shower","Shower gel","Telephone","Tile/Marble floor","Toilet","Toilet paper","Toiletries","Towels","Trash cans","TV","Wardrobe/Closet"]', '["/images/cottage-front-view1.jpg","/images/cottage4-bed1.jpg","/images/cottage4-bed-view1.jpg","/images/cottage4-washroom1.jpg","/images/path-view-1.jpg","/images/garden-view-1.jpg"]', 4, 'published');
INSERT INTO experiences (slug, title, summary, content, duration, cost, included, images, display_order, status) VALUES ('bonfire-stargazing-2', 'Bonfire & Stargazing', 'On clear nights at this elevation, the stars in Munnar feel close enough to disturb.', 'An unscheduled evening in an open grove behind the cottages, about a three-minute walk from the main buildings, positioned to keep light from interfering with the night sky. When the mist clears, the sky opens — on clear nights you can see the Milky Way overhead without any guidance needed. No set program, no fixed timing.', 'Most guests stay about an hour, though you''re welcome as long as the fire lasts.', 'Complimentary for all guests in residence', '["Fire setup and maintenance","Wooden chairs and low benches","Warm blankets","Hot beverages — chai, coffee, or hot chocolate","Guitar most nights, host-dependent"]', '["/images/bonfirre-stargazing.png","/images/bonfire-rosary-nest.png","/images/night-at-rosary-nest.png"]', 1, 'published');
INSERT INTO experiences (slug, title, summary, content, duration, cost, included, images, display_order, status) VALUES ('farm-to-table-dining', 'Farm-to-Table Dining', 'Simple food, mostly from what grows here.', 'Most ingredients come from the family''s garden or neighbouring farms — honest, seasonal cooking prepared the way the family eats, not restaurant-style. Breakfast brings fresh fruit, hot bread, eggs from their own birds, and masala chai or filter coffee, included with every stay. Lunch is light and flatbread-led, suited to Munnar''s afternoon rest. Dinner is the main event: three or four small courses, on the deck or in the dining room depending on weather. We don''t run a restaurant. We cook the way we cook for ourselves, and set a place for our guests at that table.', 'Breakfast daily; lunch and dinner on request', 'Breakfast included · lunch & dinner on request', '["Breakfast with every stay","Lunch and dinner available with a day''s notice","Vegetarian, vegan, gluten-free, Jain, and allergy accommodations","Adjusted portions and spice levels for children","Birthday cakes with advance notice"]', '["/images/nest-breakfast.png","/images/dinnerr-at-nest.png","/images/kerala-breakfast-at-rosary-nest.png"]', 2, 'published');
INSERT INTO experiences (slug, title, summary, content, duration, cost, included, images, display_order, status) VALUES ('lake-walks', 'Lake Walks', 'A short walk from the cottage, under ten minutes. Often the best part of the day.', 'A short downhill walk, under ten minutes, through tea bushes and wildflowers to a small clearing with a wooden seat by the water. Mirror-still on clear mornings, mist-veiled in fog — herons show up sometimes, or it''s just you and the water. Come at dawn, midday, or golden hour; nothing about it is scheduled.', 'Under ten minutes downhill, plus however long you stay', 'Free — no booking or schedule required', '["Access to the maintained, unpaved walking path","Walking sticks at the cottage door","A flask of chai or coffee with advance notice","Guided walks on request, led by family or staff"]', '["/images/dam-sengulam-munnar.png","/images/tea-munnar-dam.png","/images/tea-plantation.png"]', 3, 'published');
INSERT INTO experiences (slug, title, summary, content, duration, cost, included, images, display_order, status) VALUES ('forest-trails', 'Forest Trails', 'The forest is older than the cottages. Walk into it slowly.', 'Two informal trails through a managed hill forest of eucalyptus, silver oak, cardamom, and pepper — a working Western Ghats ecosystem rather than wilderness. The shorter trail is about 20 minutes return, through cardamom to a valley-view clearing. The longer loop is about an hour, crossing a small stream to an old stone wall. Mostly flat, no technical difficulty; the longer trail may close in heavy monsoon.', '20 minutes (short loop) or about an hour (long loop)', 'Complimentary', '["Hand-drawn trail map at the front desk","Walking sticks provided","First walk usually accompanied by a family member","Self-guided walks afterward","Naturalist-led walks with a day''s notice"]', '["/images/forest-trail.png","/images/garden-view-1-1.jpg","/images/path-view-wide-1.jpg"]', 4, 'published');
INSERT INTO experiences (slug, title, summary, content, duration, cost, included, images, display_order, status) VALUES ('the-pool', 'The Pool', 'A quiet plunge pool on the upper terrace, for the few afternoons Munnar gets properly warm.', 'Added more recently than the cottages, the pool sits on the upper terrace nearest the main house — unheated, and mostly reserved for the handful of warm afternoons the hills allow each year. It looks out toward the valley, so even a short swim comes with the same view as everywhere else on the property. Nothing is scheduled around it; guests use it when the light and the weather agree.', 'Open through daylight hours — ask at the house if you''d like it to yourself for a while.', 'Complimentary for all guests in residence', '["Pool towels","Loungers on the terrace","A changing area close by"]', '["/images/placeholder-coming-soon.svg"]', 5, 'published');
INSERT INTO posts (slug, title, excerpt, content, category, author, featured_image, status, published_at) VALUES ('munnar-in-monsoon-what-changes', 'Munnar in monsoon: what changes.', 'The first sign that the monsoon has arrived is never the rain. It is the silence, three or four nights running, after the cicadas stop — and then a wind comes up the valley smelling of something older than the property.', 'The first sign that the monsoon has arrived is never the rain. It is the silence, three or four nights running, after the cicadas stop — and then a wind comes up the valley smelling of something older than the property. The rain follows a day or two later, and once it starts it rarely bothers to stop properly again until September.

We stay open through June, July, and August, though we won''t pretend it''s the season most people picture when they book a hill-station holiday. The cottages fill more slowly. The family settles into a quieter rhythm — fewer guests to seat at the long table, more time to stand at the kitchen door and watch the rain come sideways across the terraces. The generator gets tested more often than it needs to be. Umbrellas live by every door, used more as a formality than a real defense against water that seems to arrive from four directions at once.

What the monsoon does to the land, it does generously. Mushrooms appear overnight in places that were bare grass a week before. The frogs get louder and, we swear, larger. Waterfalls that don''t exist in January show up on the drive in, briefly, gone again by November. This is the season we recommend to almost no one — the roads are slower, the views come and go with the mist — and it is also the one that the handful of guests who ask for it specifically never seem to forget.', 'The Land', 'The Family', '/images/monsoon-rain-munnar.png', 'published', '2026-07-12');
INSERT INTO posts (slug, title, excerpt, content, category, author, featured_image, status, published_at) VALUES ('a-morning-in-the-kitchen', 'A morning in the kitchen, when the mist hasn''t lifted.', 'Filter coffee, the radio quiet, and what we put on the long table at eight — from a kitchen that starts working two hours before any guest is awake.', 'Our cook has been in the kitchen since six. By the time most guests are stirring, the batter for the day''s appam has already had its overnight ferment checked and approved, the stew is somewhere in its second hour on a low flame, and the filter coffee has gone through its slow drip at least twice — once for the family, once, a little later, for whoever''s up first among the guests.

The radio, when it''s on at all, stays low enough to lose under the sound of the pans. Nobody in this kitchen is in a hurry, which is either the whole point of the place or a happy accident of how it was always run, even before it had guests to feed. By the time the mist starts lifting off the valley — some mornings that''s seven, some mornings closer to nine — the smell of appam and stew has usually found its way up to the veranda before the food itself does.

Breakfast isn''t plated so much as delivered to the table the way it would be delivered to family: a bit more of this if you want it, a bit less of that if the last helping didn''t sit right. Nobody at RosaryNest is on a set menu. If it''s in the kitchen and it''s ready, it''s yours.', 'Kitchen', 'The Family', '/images/kerala-breakfast-at-rosary-nest.png', 'published', '2026-04-10');
INSERT INTO posts (slug, title, excerpt, content, category, author, featured_image, status, published_at) VALUES ('the-walk-to-the-dam', 'The walk to the dam, in five hundred steps.', 'An hour down and an hour back, with a flask. The path the children take, past the white stones the lake gives up every dry season.', 'It isn''t really five hundred steps — nobody has counted properly, and the family has stopped correcting the children who insist on the number every single time. But it is roughly an hour down and an hour back, with a flask of something warm, along the same path the children have been taking for years: past the tea bushes, along the lower terrace, down to where the white stones show themselves every dry season and disappear again with the first heavy rain.

The dam itself is modest — a low wall of stone and concrete holding back water that becomes, further down the valley, somebody else''s irrigation. You can''t see the whole of it from the path; the best view is from the far ridge, a detour most guests don''t bother making on a first visit and almost always regret not making by their second. What you can see from the path is enough: still water, the occasional heron standing in it like it owns the place, and the particular quiet that comes from being somewhere with no road nearby.

We''d suggest going down in the early morning, before the mist has properly lifted, or in the last hour before dark, when the light comes in low and gold across the water. Either way, take the flask. The walk back up is slower than the walk down, and it''s a nicer place to stop for ten minutes than most.', 'Walks', 'The Family', '/images/dam-sengulam-munnar.png', 'published', '2026-03-08');
INSERT INTO posts (slug, title, excerpt, content, category, author, featured_image, status, published_at) VALUES ('whats-in-the-garden-in-february', 'What''s in the garden in February, and what isn''t.', 'The cardamom is in flower. The pepper is patient. Most of what lands on the table that evening was still in the ground at breakfast.', 'The cardamom is in flower by February, small pale clusters low on the plant, easy to miss if you''re not looking for them and impossible to miss once someone''s pointed them out. It''ll be months yet before there''s anything to harvest — cardamom asks for patience the way most things worth growing do — but the flowering is its own small event, and the family still checks the beds for it every year like it''s news.

The pepper vines climbing the silver oak are doing very little that''s visible, which is exactly what they''re supposed to be doing in February. Everything underground is working; nothing above ground is in a rush to show it. It''s a useful thing to remember about this garden generally — most of what matters here happens slowly, out of sight, on a schedule nobody''s in control of.

What does show up in February: greens, always; a stretch of good tomatoes if the frost has been kind; whatever herbs haven''t minded the cold nights. The family walks the beds most mornings before the market run into town, less to inspect than out of habit, and more often than not, whatever gets pulled that morning is what ends up on the dinner table that evening — no real distance between the garden and the plate, and no real plan beyond what''s ready.', 'Garden', 'The Family', '/images/tea-plantation.png', 'published', '2026-02-14');
INSERT INTO posts (slug, title, excerpt, content, category, author, featured_image, status, published_at) VALUES ('how-we-came-to-keep-a-guesthouse', 'How we came to keep a guesthouse, by accident.', 'My grandfather grew cardamom. My father, briefly, sold it. I make beds — and none of it was planned quite this way.', 'My grandfather farmed this land. He planted the first cardamom here, on terraces he cut into the hill himself, and he farmed it the way people farmed then — through good seasons that paid for the next bad one, and bad ones that tested whether the family would keep at it. My father inherited that same rhythm and, for a while, the same trade: cardamom mostly, with pepper and a little coffee at the edges, sold the way it had always been sold, through the same routes and the same buyers his father had used.

By 2009 the arithmetic had stopped working the way it once did. Prices had gone thin, the seasons had gotten harder to predict, and the family that had once worked this land together had, like most families, scattered a little — some to the city, some abroad, none of them farming full-time anymore. My father stopped working the plantation the way it had been worked for two generations, and for a while nobody quite knew what the land was for.

What we didn''t want to do was sell it, or let it sit empty and slowly go back to forest on its own terms. So we did something closer to the opposite: we opened it up. One cottage first, built more or less where a barn used to stand, then a second, then two more, each one going up between the trees that were already there rather than clearing space for something grander. We are not innkeepers by training or temperament. We are a family who happened to have some land we loved and a few extra rooms, and who decided that sharing both was better than watching either sit idle. I still don''t think of myself as running a hotel. Mostly, I just make sure the beds are ready before anyone arrives to sleep in them.', 'The Family', 'The Family', '/images/garden-view-1.jpg', 'published', '2026-01-20');
INSERT INTO posts (slug, title, excerpt, content, category, author, featured_image, status, published_at) VALUES ('appam-in-the-slow-way', 'Appam, in the slow way.', 'A lace pancake that takes a day to start and ten minutes to make — and, according to our cook, is always better on the second day.', 'Appam has a reputation for being difficult that it doesn''t entirely deserve — what it actually demands is patience rather than skill. The batter is rice and coconut, blended fine, left to ferment overnight with a little help from toddy or yeast depending on who''s making it and what''s on hand. By morning it should have risen and gone faintly sour in the good way, bubbling gently if you tap the bowl.

Our cook swears, with the confidence of someone who has made this thousands of times, that second-day batter always makes better lace than first-day batter — something about the fermentation settling into itself overnight that a few extra hours won''t replicate if you rush it. We''ve never found a reason to argue with her about it.

Cooking it is the fast part: a hot, well-seasoned appachatti, a ladle of batter swirled quickly around the edges so it thins out to lace at the rim and stays soft and a little spongy in the center, a lid on for a minute or two, and it''s done. Served with a vegetable stew, or with the sweet coconut milk version we sometimes make for a slower Sunday breakfast, it''s the kind of dish that rewards someone who started it the night before and disappoints anyone trying to shortcut it the same morning.', 'Recipes', 'The Family', '/images/nest-breakfast.png', 'published', '2025-12-05');
INSERT INTO faqs (question, answer, category, display_order) VALUES ('What is your cancellation policy?', 'Write to us at stay@rosarynest.com and we''ll walk you through booking and cancellation.', 'Before you book', 1);
INSERT INTO faqs (question, answer, category, display_order) VALUES ('How do I pay, and when?', 'Write to us at stay@rosarynest.com and we''ll walk you through booking and cancellation.', 'Before you book', 2);
INSERT INTO faqs (question, answer, category, display_order) VALUES ('Can we bring children?', 'Yes, gladly. We don''t have a kids'' club or a babysitter on staff, and there''s a fast-flowing stream below the lower terrace, so toddlers need supervision. Older children (eight and up) tend to love the place.', 'Before you book', 3);
INSERT INTO faqs (question, answer, category, display_order) VALUES ('Do you accept pets?', 'We don''t, mainly because the property has two resident dogs and a half-feral kitchen cat who would rather not share. Service animals are an exception — please tell us in advance.', 'Before you book', 4);
INSERT INTO faqs (question, answer, category, display_order) VALUES ('Is the property accessible?', 'Some cottages involve steps and uneven paths — tell us about mobility needs when you book and we''ll recommend the right one.', 'Before you book', 5);
INSERT INTO faqs (question, answer, category, display_order) VALUES ('How bad is the road in monsoon?', 'The main road is fine — a well-maintained state highway. The last three kilometres up to the property are slow and slippery in heavy rain. We can send a 4×4 from Munnar town if your driver isn''t comfortable with the last stretch.', 'Getting here', 1);
INSERT INTO faqs (question, answer, category, display_order) VALUES ('What if I arrive late?', 'We''ll wait up. Write or call as soon as you know — we''ll keep the kitchen open and walk you up from the gate with a lantern. There''s no surcharge for late arrival.', 'Getting here', 2);
INSERT INTO faqs (question, answer, category, display_order) VALUES ('Is there parking?', 'Yes, sixty metres below the upper veranda. Covered, secure, and within easy walking distance of every cottage.', 'Getting here', 3);
INSERT INTO faqs (question, answer, category, display_order) VALUES ('What time is check-in and check-out?', 'Check-in from 2 pm, check-out by 11 am. Early arrival or late departure usually works — ask when you book and we''ll do what we can.', 'Your stay', 1);
INSERT INTO faqs (question, answer, category, display_order) VALUES ('I''m vegetarian / gluten-free / allergic to —. Will that work?', 'Yes. Tell us in advance and our cook will plan around it. Our kitchen is fundamentally Kerala — rice, coconut, vegetables, fresh fish — and adapts easily. We don''t do a buffet, so no cross-contamination concerns.', 'Your stay', 2);
INSERT INTO faqs (question, answer, category, display_order) VALUES ('Do you serve alcohol?', 'We don''t have a bar. You''re welcome to bring your own wine, beer, or spirits, and we''ll provide glassware, ice, and a corkscrew. The closest off-licence is in Munnar town, twenty minutes away.', 'Your stay', 3);
INSERT INTO faqs (question, answer, category, display_order) VALUES ('Is there wifi?', 'Yes, throughout the property, though it slows in heavy rain. Strong enough for email, video calls, and a film if you must. Not strong enough for serious work — and we''d quietly prefer that you didn''t try.', 'Your stay', 4);
INSERT INTO faqs (question, answer, category, display_order) VALUES ('Can I get laundry done?', 'Yes, same-day if it''s in by 9 am, weather permitting. Hand-washed, sun-dried, folded. There''s no charge for a small load; longer stays get a small bill at the end.', 'Your stay', 5);
INSERT INTO faqs (question, answer, category, display_order) VALUES ('What''s there to do off the property?', 'More than you''d think. Tea-estate walks, Eravikulam Park, the dam, Top Station, the spice plantations. We have a small set of curated routes; ask at breakfast and we''ll print you a sheet.', 'Things to do', 1);
INSERT INTO faqs (question, answer, category, display_order) VALUES ('Do you work with the surrounding tea estates?', 'Yes — three of them. We can arrange a tea-pluck-and-taste morning, lunch in a planter''s bungalow, or a guided walk through the higher slopes. All small, all by appointment.', 'Things to do', 2);
INSERT INTO faqs (question, answer, category, display_order) VALUES ('Can you arrange a driver for the day?', 'Yes, our driver brings most guests up from Cochin and knows where to stop and where not to — we can arrange this, ask us when you book.', 'Things to do', 3);
INSERT INTO faqs (question, answer, category, display_order) VALUES ('Which cottage should I pick?', 'Quietest is Sparrow Hut. Most reading-friendly is Tarry Cottage. Best for valley sunsets is Eyrie Cottage. Write to us and we''ll help you find the right fit, including for Scarlet Hut.', 'The cottages', 1);
INSERT INTO faqs (question, answer, category, display_order) VALUES ('Is there room service?', 'Tea and breakfast can come to your veranda. Lunch and dinner are at the long table, weather permitting, or in the dining room when it isn''t. We''ll bring dinner to the cottage if you ask.', 'The cottages', 2);
INSERT INTO faqs (question, answer, category, display_order) VALUES ('Can we have extra bedding?', 'Always. Wool blankets, cotton throws, hot-water bottles in January. Just ask, or pull what you need from the linen cupboard in your cottage.', 'The cottages', 3);
INSERT INTO gallery_items (image_url, caption, category, display_order) VALUES ('/images/munnar-beauty.jpg', 'Valley at first light, late January.', 'land', 1);
INSERT INTO gallery_items (image_url, caption, category, display_order) VALUES ('/images/cottage-front-view1.jpg', 'Eyrie Cottage, west veranda.', 'cottages', 2);
INSERT INTO gallery_items (image_url, caption, category, display_order) VALUES ('/images/kerala-breakfast-at-rosary-nest.png', 'Appam, stew, banana leaf.', 'food', 3);
INSERT INTO gallery_items (image_url, caption, category, display_order) VALUES ('/images/dam-sengulam-munnar.png', 'The lake, six in the morning.', 'land', 4);
INSERT INTO gallery_items (image_url, caption, category, display_order) VALUES ('/images/monsoon-rain-munnar.png', 'Tea slope, second week of July.', 'seasons', 5);
INSERT INTO gallery_items (image_url, caption, category, display_order) VALUES ('/images/veranta-view-3.jpg', 'Outdoor veranda, Sparrow Hut.', 'cottages', 6);
INSERT INTO gallery_items (image_url, caption, category, display_order) VALUES ('/images/dinnerr-at-nest.png', 'The long table, dinner.', 'food', 7);
INSERT INTO gallery_items (image_url, caption, category, display_order) VALUES ('/images/path-view-1.jpg', 'The lower path to the dam.', 'land', 8);
INSERT INTO gallery_items (image_url, caption, category, display_order) VALUES ('/images/bedroom-view-3.jpg', 'Inside Sparrow Hut at noon.', 'cottages', 9);
INSERT INTO gallery_items (image_url, caption, category, display_order) VALUES ('/images/tea-plantation.png', 'Tea slope below the property.', 'seasons', 10);
INSERT INTO gallery_items (image_url, caption, category, display_order) VALUES ('/images/nest-breakfast.png', 'Breakfast on the veranda.', 'food', 11);
INSERT INTO gallery_items (image_url, caption, category, display_order) VALUES ('/images/hut-main-view-1.jpg', 'Scarlet Hut, exterior view.', 'cottages', 12);
INSERT INTO gallery_items (image_url, caption, category, display_order) VALUES ('/images/garden-view-1.jpg', 'The garden, early morning.', 'land', 13);
INSERT INTO gallery_items (image_url, caption, category, display_order) VALUES ('/images/bonfire-rosary-nest.png', 'Bonfire, cold-season evening.', 'seasons', 14);
INSERT INTO gallery_items (image_url, caption, category, display_order) VALUES ('/images/red-cottage-front-view.png', 'Tarry Cottage, front view.', 'cottages', 15);
INSERT INTO gallery_items (image_url, caption, category, display_order) VALUES ('/images/bamboo-cafe.png', 'The bamboo café, midday light.', 'food', 16);
