import imageManifest from "@/lib/image-manifest.json";

type ManifestEntry = { width: number; height: number; webp: string; srcset: string };
const manifest = imageManifest as Record<string, ManifestEntry>;

type SiteImageProps = Omit<React.ImgHTMLAttributes<HTMLImageElement>, "src" | "alt"> & {
  src: string;
  alt: string;
  /** Mark the one LCP-candidate image per page — skips lazy-loading and hints the browser to fetch it first. */
  priority?: boolean;
  /**
   * How much of the viewport this image actually occupies at each breakpoint,
   * e.g. "(max-width: 1024px) 100vw, 25vw" for a 4-up desktop grid that
   * collapses to one column on mobile. Defaults to full-width, which is
   * always correct but only makes sense for hero/full-bleed images — grid
   * and thumbnail usages should pass a real value so mobile doesn't fetch a
   * desktop-width file for a quarter-width card.
   */
  sizes?: string;
};

/**
 * Drop-in replacement for <img>: serves a WebP version (generated by
 * scripts/convert-to-webp.mjs) — with a srcset of a few smaller widths so
 * mobile doesn't download a desktop-resolution file — falling back to the
 * original format as a <picture> fallback, and sets explicit width/height
 * from the build-time manifest so the browser can reserve layout space
 * before the image loads.
 *
 * Falls back to a plain <img> with no dimensions for sources that aren't in
 * the manifest (e.g. user-uploaded R2 media) rather than failing.
 */
export function SiteImage({ src, alt, priority, sizes = "100vw", ...rest }: SiteImageProps) {
  const entry = manifest[src];

  if (!entry) {
    return <img src={src} alt={alt} loading={priority ? undefined : "lazy"} {...rest} />;
  }

  return (
    <picture>
      <source srcSet={entry.srcset} sizes={sizes} type="image/webp" />
      <img
        src={src}
        alt={alt}
        width={entry.width}
        height={entry.height}
        loading={priority ? undefined : "lazy"}
        fetchPriority={priority ? "high" : undefined}
        {...rest}
      />
    </picture>
  );
}
